# Generated by Django 2.0.5 on 2018-05-13 09:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('name', models.CharField(max_length=100, verbose_name='Имя файла')),
                ('description', models.TextField(max_length=240, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файл')),
                ('dc', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dm', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('dd', models.DateTimeField(null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
            },
        ),
    ]
