# ansible-playbook -i ansible/inventory -u root -v ansible/install.yml

- name: Install SONM CMS
  hosts: all

  tasks:
    - name: prepare install docker
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo apt-key fingerprint 0EBFCD88
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: install packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - docker-ce
        - python-pip
        - nginx

    - name: install docker-py
      pip:
        name: docker-py
        version: 1.10.6

    - name: "remove old {{ service_name }} instance"
      docker_container:
        image: "dessanndes/sonm-{{ service_name }}"
        name: "{{ service_name }}"
        state: absent

    - name: create web-static directory
      file:
        path: "/var/www/{{ service_name }}/static"
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: create conf directory
      file:
        path: "/conf/sonm-{{ service_name }}"
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: create settings
      template:
        src: local_settings.py.jinja2
        dest: "/conf/sonm-{{ service_name }}/local_settings.py"
        mode: 0600

    - name: "start {{ service_name }}"
      docker_container:
        name: "{{ service_name }}"
        image: "dessanndes/sonm-{{ service_name }}"
        pull: yes
        ports:
          - 127.0.0.1:{{ service_port }}:{{ service_port }}
        volumes:
          - "/data/sonm-{{ service_name }}:/data"
          - "/conf/sonm-{{ service_name }}:/conf"
          - "/var/www/{{ service_name }}/static:/static"

    - name: remove nginx default
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: create nginx config
      template:
        src: nginx.jinja2
        dest: "/etc/nginx/sites-enabled/{{ service_name }}"

    - name: reload nginx
      service:
        name: nginx
        state: reloaded