# ansible-playbook -i ansible/inventory -u root -v ansible/install.yml

- name: Install SONM CMS
  hosts: all

  tasks:

    - name: install packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - docker.io
        - python-pip
        - nginx

    - name: install docker-py
      pip:
        name: docker-py
        version: 1.10.6

    - name: remove old sonm-cms instance
      docker_container:
        name: sonm-cms
        image: dessanndes/sonm-cdn
        state: absent

    - name: create web-static directory
      file:
        path: "/var/www/sonm-cms/static"
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: create conf directory
      file:
        path: "/conf/sonm-cms"
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: create settings
      template:
        src: local_settings.py.jinja2
        dest: "/conf/sonm-cms/local_settings.py"
        mode: 0600

    - name: start sonm-cms
      docker_container:
        image: dessanndes/sonm-cms
        name: sonm-cms
        pull: yes
        ports:
          - 127.0.0.1:{{ service_port }}:80
        volumes:
          - "/data/sonm-cms:/data"
          - "/conf/sonm-cms:/conf"
          - "/var/www/sonm-cms/static:/static"

    - name: remove nginx default
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: create nginx config
      template:
        src: nginx.jinja2
        dest: "/etc/nginx/sites-enabled/sonm-cms"

    - name: reload nginx
      service:
        name: nginx
        state: reloaded